### ISSUE TITLE
Incorrect ModelTrainer() arguments in tutorials

### ISSUE THREAD

**Issue by Aatlantise** [Alibaba-NLP/ACE#10]
Hello,

Thank you for your extensive tutorials. They have been very helpful.

I came across a minor error in the tutorial code, however. The first keyword argument while initializing the ModelTrainer object is a teacher model, rather than corpus. So, lines like `trainer: ModelTrainer = ModelTrainer(tagger, corpus)` in https://github.com/Alibaba-NLP/ACE/blob/main/resources/docs/EXPERIMENTS.md return an attribute error that can be fixed with `trainer: ModelTrainer = ModelTrainer(tagger, corpus = corpus)`

**Comment by wangxinyu0922** [comment]
Hi, 

I modified the code of flair a lot, therefore please follow the [README.md](https://github.com/Alibaba-NLP/ACE#readme) in the main directory to run our code. The [EXPERIMENTS.md](https://github.com/Alibaba-NLP/ACE/blob/main/resources/docs/EXPERIMENTS.md) is the old guide in flair. I'm sorry for the guide that misleads you. I will delete the EXPERIMENTS.md in the next commit.

**Comment by Aatlantise** [comment]
Gotcha. Thanks for your clarifications :)
