### ISSUE TITLE
Ask about results in Table 2.

### ISSUE THREAD

**Issue by fym0503** [Alibaba-NLP/ACE#17]
![image](https://user-images.githubusercontent.com/48177486/130346477-a193acb3-9f05-4076-9fbf-2d1a4cfc45e3.png)
Hi, I read your paper and find in Table 2, for NER tasks on Es, your methods bring very large gains compared with other languages. Do you have some intuition on why it can bring such large gains ?

**Comment by wangxinyu0922** [comment]
The BERT model we used for es is a finetuned model from [huggingface models](https://huggingface.co/mrm8488/bert-spanish-cased-finetuned-ner/tree/main). I'm not sure whether the model is trained with a wrong dataset split on CoNLL dataset and I find that the dataset split in README.md is not identical to the official dataset split. I may try to use another Spanish BERT model for the dataset later.

**Comment by fym0503** [comment]
Ok, I understand.
