### ISSUE TITLE
Implementation of Abstract Extraction

### ISSUE THREAD

**Issue by ntdas** [Alibaba-NLP/ACE#18]
Thank you for your awesome work, but after looking at part of the code I realized the training code for abstract Extraction is currently under "rejected list". Could you explain a little bit how you obtained the results for SentEval dataset? I am trying to reproduce the results and hopefully use them for my own project.

Sincerely.

**Comment by wangxinyu0922** [comment]
Hi,

I'm not sure the meaning of the "rejected list". We take the task as a sequence labeling task and format the datasets into BIO formats. I think you may need the aspect extraction datasets and I uploaded it on [Onedrive](https://1drv.ms/u/s!Am53YNAPSsodg9gv-4fMEySIUXDP3g?e=zJpIjw). You can follow the guide in [README](https://github.com/Alibaba-NLP/ACE#Instructions-for-Reproducing-Results) to train your model.

**Comment by ntdas** [comment]
Thanks for clarifying, I will look into it more carefully.
