### ISSUE TITLE
System requirements for implementing it

### ISSUE THREAD

**Issue by knitemblazor** [Alibaba-NLP/ACE#19]
i would like to know about the system requirements for running this effectively as i am facing issues with my build of 32 gb cpu ram nvidia 1080 of 12 gb

**Comment by wangxinyu0922** [comment]
HI, 

The code requires large cpu memory ~50gb. For the GPU issue, you may reduce the batch size during training.

**Comment by knitemblazor** [comment]
ok thank you for the response
