### ISSUE TITLE
support for enhanced++ dependencies

### ISSUE THREAD

**Issue by LifeIsStrange** [Alibaba-NLP/ACE#20]
cf https://aclanthology.org/L16-1376.pdf

**Comment by wangxinyu0922** [comment]
Hi,

I haven't read the paper carefully yet, but I think the enhanced++ dependencies are similar to the [enhanced universal dependencies](https://universaldependencies.org/u/overview/enhanced-syntax.html). You may refer to preprocessing in [Wang et al. 2021](https://arxiv.org/abs/2107.02416), [Wang et al. 2020](https://arxiv.org/abs/2006.01414) and run the code according to the SDP formatting.
