### ISSUE TITLE
requirements.txt facing conflicts

### ISSUE THREAD

**Issue by harpap** [Alibaba-NLP/ACE#25]
Can anyone confirm if it is possible to run the command:

`pip install -r requirements.txt`

and face zero conflicts? 

I am trying to run it on newly created conda envs and I face 2 conflicts. 

1. on `mkl-fft==1.0.6` and
2. on `numpy==1.15.1`

Thanks in advance

**Comment by wangxinyu0922** [comment]
Hi, you may refer to this [issue](https://github.com/Alibaba-NLP/ACE/issues/5#issuecomment-873810236)

**Comment by harpap** [comment]
> Hi, you may refer to this [issue](https://github.com/Alibaba-NLP/ACE/issues/5#issuecomment-873810236)

Thank you!
