### ISSUE TITLE
About config for tweebank dataset

### ISSUE THREAD

**Issue by hary00078** [Alibaba-NLP/ACE#3]
Hello 
First of all, I read the your paper published well. I was very impressed. I applied uploaded code to the CoNLL 2003 data set. I confirmed the performance suggested in the  paper.
This time,  I want to confirm performance about POS with Tweebank data set. But I can't confirm proper performance. So shall you send me the yaml file for POS? Thanks for reading.

**Comment by wangxinyu0922** [comment]
Hi, I have uploaded the config file. You can find the config file in [config/](https://github.com/Alibaba-NLP/ACE/blob/main/config/tweebank_finetune_pos.yaml). Before train the model, you need to finetune `BERT`, `M-BERT` and `XLM-R` on the tweebank at first. You can find the guide for finetuning transformer-based models at: [https://github.com/Alibaba-NLP/ACE#optional-fine-tune-transformer-based-embeddings](https://github.com/Alibaba-NLP/ACE#optional-fine-tune-transformer-based-embeddings)

**Comment by hary00078** [comment]
Thank you. I'll do it right away
