### ISSUE TITLE
下载bert-base-multilingual-cased.hdf5的问题

### ISSUE THREAD

**Issue by gly99999** [Alibaba-NLP/ACE#32]
由于这个模型在OneDrive上，而且有19个g，所以在国内下载这个模型在下载链接失效前总是下载不完，国内有其他的网盘或者链接可以下载吗，感谢~

**Comment by wangxinyu0922** [comment]
百度云有上传限制，不太好搞，我现在把文件分成了10个2G的`bert-base-multilingual-cased.hdf5.part*`文件放在onedrive上，正在上传中，过一会就可以自行下载

**Comment by gly99999** [comment]
好的，非常感谢

**Comment by junwei-h** [comment]
how to merge multiple bert-base-multilingual-cased.hdf5.part* to a single file? Or is it necessary?

**Comment by wangxinyu0922** [comment]
> how to merge multiple bert-base-multilingual-cased.hdf5.part* to a single file? Or is it necessary?
```bash
cat bert-base-multilingual-cased.hdf5.part* > bert-base-multilingual-cased.hdf5
```
