### ISSUE TITLE
Parsed order for prediction of test set is randomized

### ISSUE THREAD

**Issue by tanpengshi** [Alibaba-NLP/ACE#36]
I have tried to run:

`CUDA_VISIBLE_DEVICES=0 python train.py --config config/nergrit_indo.yaml --parse --target_dir $dir --keep_order`

for a indonesian NER dataset trained with ACE. However in the ouput .conllu file, the output sentence order is always randomized, each time I run the command, and does not match the sentence order in my test set.

Kindly assist, thank you!

**Comment by wangxinyu0922** [comment]
It's strange. [This line](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/train.py#L339) will let the code keep the order of the input data if `--keep_order` is activated. Have you changed the code of `train.py`?

**Comment by tanpengshi** [comment]
I did change the codes in flair.datasets.py

This is because my Indonesian dataset only has 2 columns, while the original data format has 4 columns. Furthermore, i do not have the '-DOCSTART- -X- -X- O' line, as it is a single document

Could this change be a problem?

The other big issue I encountered was the number of lines created by the .conllu file is less than the lines in the test set. On top of the sentences being randomized

**Comment by wangxinyu0922** [comment]
The `train.py` read the parse dataset with 2 columns [by default](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/train.py#L337). I think you don't need to change the `flair/datasets.py`. For the output .conllu file, have you checked the number of sentences is the same as the input file? Maybe you can give some screenshots/examples for the issue you met.

**Comment by tanpengshi** [comment]
For the output .conllu file, the number of sentences is much lesser than that in the input file. The screenshot of the beginning of the input file is:

![image](https://user-images.githubusercontent.com/24505990/165875689-002a31c6-a1fe-40f7-ab5a-23bc31556413.png)

The screenshot of the beginning of the output .conllu file is:

![image](https://user-images.githubusercontent.com/24505990/165875971-cc5ca660-3db5-4fb5-a9fd-d8aed77e4043.png)

**Comment by tanpengshi** [comment]
In the flair/datasets.py, I have to copy/paste a new class:

![image](https://user-images.githubusercontent.com/24505990/165877729-06005177-3296-4c52-be4f-9c4b90fd1882.png)

I also have to change: `columns = {0: "text", 1: "pos", 2: "chunk", 3: "ner"}` to `columns = {0: "text", 1: "ner"}`, if not data parsing will throw an error when I run the command.

**Comment by wangxinyu0922** [comment]
How do you change the code of [train.py](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/train.py#L339)? Since you are using a different corpus class for your dataset, the [train.py](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/train.py#L339) should be changed accordingly. Moreover, I believe you do not need to create a new class for it since `ColumnCorpus` in [train.py](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/train.py#L339) reads two-column format by default.

By the way, can I take a look for your config file?

**Comment by tanpengshi** [comment]
I actually did not change anything in the code train.py, although I did copy and paste a new class NERGRIT in flair/datasets.py, with only changes to the column variable.

Interestingly while I was doing debugging, I stumbled across a functional solution. In the class ColumnCorpus in flair/datasets.py:

![image](https://user-images.githubusercontent.com/24505990/166639752-b3dd3a49-b201-42f4-b755-57d419163139.png)

The train variable did has the right number and right order of test sentences. Hence, I created a new attribute to the class:

![image](https://user-images.githubusercontent.com/24505990/166640095-1e813cdf-00f0-4612-9452-95bfe31e6e27.png)

Then in train.py, i changed corpus.train into corpus.training in the below script, and this solved the bug.

![image](https://user-images.githubusercontent.com/24505990/166640505-eef0df0b-a51a-4bc7-91d6-6fedfb5d01d6.png)

**Comment by wangxinyu0922** [comment]
In the last line of the `__init__()` of [class ColumnCorpus](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/flair/datasets.py#L127), the code will initialize the `class Corpus` in [flair/data.py](https://github.com/Alibaba-NLP/ACE/blob/ce6c65d1f65820b4f321e47c32a1d94aa14107d1/flair/data.py#L840), which assigns the property of the class `self.train=train`. 

I'm not sure what happened in your environment, but I'm glad to know you have solved the bug.

**Comment by junwei-h** [comment]
I have the same problem. @tanpengshi 's method works but hacky. The problem is when `--parse` is used, the code shall not split 10% of train data for test or dev data as this is not training but inference. See https://github.com/Alibaba-NLP/ACE/blob/main/flair/datasets.py#L107

Would be great if the author can clean up the logic.
