### ISSUE TITLE
Confuse about the SDP dataset

### ISSUE THREAD

**Issue by iamownt** [Alibaba-NLP/ACE#39]
When I run train.py with config-psd_parsing_model.yaml, I encounter “FileNotFoundError: [Errno 2] No such file or directory: '/home/rnx/.flair/datasets/enhanced_ud/PSD' Error, which indicates that neither do I  have  train, Dev and test of PSD, DM and PAS datasets nor I know about how to preprocess them. Could you provide some tips on how to get and preprocess data sets? Do I need to buy dataset from https://catalog.ldc.upenn.edu/LDC2016T10？

**Comment by wangxinyu0922** [comment]
You should buy the dataset from LDC and use the preprocess script at [https://github.com/tdozat/Parser-v3/tree/master/scripts](https://github.com/tdozat/Parser-v3/tree/master/scripts) to convert the file into conll format

**Comment by iamownt** [comment]
Thanks for your help. Wish you great successes in your future PhD carrer.
