### ISSUE TITLE
Could you provide google-colab notebook?

### ISSUE THREAD

**Issue by ahmad-alismail** [Alibaba-NLP/ACE#4]
Hello, 
I am a little bit beginner but I am very interested to implement your method for aspect extraction with google-colab or kaggle notebook...
I hope if you could provide one or give me a link if the notebook exists.

Thank you in advance...

**Comment by kankajan814** [comment]
I am interested too...
If someone could help me to implement this method using colab notebook I can pay for him...

**Comment by wangxinyu0922** [comment]
I'm sorry. I have no experience of using the two notebooks. Is there anyone can help?
