### ISSUE TITLE
Using your best model for inference for NER in production

### ISSUE THREAD

**Issue by Dimiftb** [Alibaba-NLP/ACE#45]
Hi there, 

Is there an easy way to use your pre-trained model for inference? If not, do you have plans perhaps to release it in huggingface or any other place so that we can use it in production as you still hold the SOTA on CoNLl dataset?

Thanks

**Comment by wangxinyu0922** [comment]
Hi, you can follow the guide in [named_entity_recognition.md](https://github.com/Alibaba-NLP/ACE/blob/main/resources/docs/named_entity_recognition.md) for inference. I have no plan to release it in huggingface currently.

**Comment by Dimiftb** [comment]
Hi @wangxinyu0922 

Appreciate your response. I'm struggling to find the particular information. 

Let's say I've got a sentence "Berlin is a great city". How would I go about running the model on it so that I can extract the named entities. 

Could you please point me to the exact location in the readme file where I can read about how to achieve that if it's there? 

Thank you.

**Comment by wangxinyu0922** [comment]
Check [this part](https://github.com/Alibaba-NLP/ACE#parse-files) first, which guides the predict file formatting and how to use the model for predictions.

**Comment by Dimiftb** [comment]
Appreciate your help.
