### ISSUE TITLE
Missing B-ORG but with I-ORG and E-ORG

### ISSUE THREAD

**Issue by junwei-h** [Alibaba-NLP/ACE#46]
I wonder if anyone else hit the situation where B-ORG is missing but I-ORG, E-ORG are in the tag. 

Moonstone is tagged as I-ORG without a B-ORG. I thought a tag will always start with a "B-" tag, like an open parenthesis followed by a close parenthesis. Any ideas what may cause this case? Thank you. 

```
Mount O B-LOC 0.9758268594741821
St O I-LOC 0.9999212026596069
Louis O E-LOC 0.9446600675582886
Moonstone O I-ORG 0.5030291080474854
Ski O I-ORG 0.9011916518211365
Resort O I-ORG 0.6022846102714539
Ltd O E-ORG 0.9203924536705017
```

**Comment by wangxinyu0922** [comment]
The CRF layer does not force all the tag sequences should be correct (but it helps). I suggest you may manually fix these problem (I-ORG->B-ORG for moonstone)

**Comment by junwei-h** [comment]
Thank you
