### ISSUE TITLE
Trying to download pretrained models

### ISSUE THREAD

**Issue by Jordy-VL** [Alibaba-NLP/ACE#7]
Hi, 

I was trying to download the pretrained models from Onedrive, yet I have an issue with _conll_en_ner_model.zip_. 

After 2.4GB in I get the following message: 

2021-03-12 09:11:40 (782 KB/s) - Read error at byte 2581894817/4107054003 (Connection reset by peer). Retrying.

This might suggest the download is corrupt. Is there any other way to share that specific zip? Thanks!

**Comment by wangxinyu0922** [comment]
I have uploaded the model on [Google Drive](https://drive.google.com/file/d/1MWNk_zDO0_74anaYW9X5w5moYW8b-bE3/view?usp=sharing).
