### ISSUE TITLE
Unable to download sequence tagger model due to updated links at flair

### ISSUE THREAD

**Issue by Aatlantise** [Alibaba-NLP/ACE#9]
Hello,

First, thank you for your exciting work in concatenating embeddings for use in downstream tasks. I am looking forward to trying it out.

I attempted to download sequence tagger models, but found out that links included in your fork of flair is outdated, and the AWS links like https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models-v0.4 have been replaced with the likes of https://nlp.informatik.hu-berlin.de/resources/models.

The flair update is documented here: https://github.com/flairNLP/flair/issues/1831

Much thanks!

**Comment by wangxinyu0922** [comment]
Hi,

Thank you to inform me about this information. I updated some of the download links 3 months ago. I just now checked again and found that most of the download links are identical to the newest version of Flair. Could you tell me which embedding you failed to download? So that I can check it.

**Comment by Aatlantise** [comment]
Thank you for your quick response. I was attempting to download a SequenceTagger model for chunking.

I fixed the error by modifying lines 1449 and 1548 of https://github.com/Alibaba-NLP/ACE/blob/main/flair/models/sequence_tagger_model.py.
